from app.core.models import ExchangeName


CASH_CARRY_EXCHANGES = (ExchangeName.GATE, ExchangeName.BITGET)
CASH_CARRY_EXCHANGE_SET = set(CASH_CARRY_EXCHANGES)
CASH_CARRY_INTERNAL_CANDIDATE_LIMIT = 200
CASH_CARRY_DISPLAY_CANDIDATE_LIMIT = 50
